// react-form/src/Form.jsx
import React, { useState } from 'react';
import './Form.css';

function Form() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');

  const handleSubmit = (event) => {
    event.preventDefault(); 
    if (!name || !email) {
      alert('Por favor, preencha todos os campos.');
      return;
    }
    alert(`Formulário React Enviado!\nNome: ${name}\nEmail: ${email}`);
    setName('');
    setEmail('');
  };

  return (
    <div className="form-wrapper-react">
      <h3>Formulário Construído em React</h3>
      <form onSubmit={handleSubmit}>
        <div className="form-group">
          <label htmlFor="name">Nome:</label>
          <input
            type="text"
            id="name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Seu nome"
          />
        </div>
        <div className="form-group">
          <label htmlFor="email">Email:</label>
          <input
            type="email"
            id="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="seu@email.com"
          />
        </div>
        <button type="submit">Enviar</button>
      </form>
    </div>
  );
}

export default Form;

// angular-form/src/app/form/form.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-form',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule
  ],
  templateUrl: './form.component.html', 
  styleUrls: ['./form.component.css']    
})
export class FormComponent { 
  name: string = '';
  email: string = '';
  handleSubmit() {
    if (!this.name || !this.email) {
      alert('Por favor, preencha todos os campos.');
      return;
    }
    alert(`Formulário Angular Enviado!\nNome: ${this.name}\nEmail: ${this.email}`);
    this.name = '';
    this.email = '';
  }
}
<div class="form-wrapper-angular">
    <h3>Formulário Construído em Angular</h3>
    <form (ngSubmit)="handleSubmit()">
      <div class="form-group">
        <label for="name">Nome:</label>
        <input type="text" id="name" name="name" [(ngModel)]="name" placeholder="Seu nome">
      </div>
      <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" [(ngModel)]="email" placeholder="seu@email.com">
      </div>
      <button type="submit">Enviar</button>
    </form>
  </div>
